### ISSUE TITLE
is this necessary? 

### ISSUE THREAD

**Issue by sljmn** [yshmarov/insta2blog.com#81]
```
def call
    insta_user_data = ask_user_profile
    insta_user = InstaUser.find_or_initialize_by(username: insta_user_data['username'])
    insta_user.update(
      remote_id: insta_user_data['id'],
      account_type: insta_user_data['account_type'].downcase,
      media_count: insta_user_data['media_count']
    )
    insta_user
  end
```
is the [insta_user](https://github.com/yshmarov/insta2blog.com/blob/6a9c7e3162a24bad755da52161072ca6186c5835/app/services/insta_me_service.rb#L17) necessary? Wouldnt insta_user.update already return what you want?

btw love to follow this project, very cool see you hacking on it! learning a lot!

**Comment by yshmarov** [comment]
Thanks for your comment! 

However the `update` is returning `true` here, so that's why I have to explicitly get the `insta_user` once more:

<img width="1055" alt="Screenshot 2022-11-10 at 23 27 38" src="https://user-images.githubusercontent.com/13472945/201219387-77747d7f-91bb-4453-b1c5-f12aec7f3e93.png">

At moments like this I'm happy to have invested the time into adding some tests 😝

**Comment by sljmn** [comment]
hehe very nice!
